spring:
  data:
    mongodb:
      database: notification
      port: 27017
      auto-index-creation: true
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092
email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
server:
  port: 8097